name: medics
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  mask_text_input_formatter: ^2.9.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.3
  dio: ^5.7.0
  connectivity_plus: ^6.0.5
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  provider: ^6.1.2
  flutter_native_splash: ^2.4.2
  go_router: ^14.5.0
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/program/
  
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/static/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/static/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/static/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/static/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/static/Inter_18pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/static/Inter_18pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/static/Inter_18pt-Light.ttf
          weight: 300

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/src/common/l10n/
  output_dir: lib/src/common/l10n/generated/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
