name: medics
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.1
  flutter_svg: ^2.0.14
  mask_text_input_formatter: ^2.9.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.3
  dio: ^5.7.0
  connectivity_plus: ^6.0.5
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  provider: ^6.1.2
  equatable: ^2.0.7
  flutter_native_splash: ^2.4.2
  go_router: ^14.5.0
  pinput: ^5.0.0
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/

  
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/static/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/static/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/static/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/static/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/static/Inter_18pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/static/Inter_18pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/static/Inter_18pt-Light.ttf
          weight: 300

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/src/common/l10n/
  output_dir: lib/src/common/l10n/generated/



flutter_native_splash:
  color: "#199A8E"
  color_dark: "#199A8E"
  color_android: "#199A8E"
  color_ios: "#199A8E"
  image: assets/images/splash_logo.png
  image_dark: assets/images/splash_logo.png
  android_12:
    image: assets/images/splash_logo.png
    image_dark: assets/images/splash_logo.png
  android: true
  ios: true

  
  
flutter_launcher_icons:
  image_path_android: "assets/images/app_logo.png"
  image_path_ios: "assets/images/app_logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/app_logo.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/app_logo.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground_inset: 16 # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/images/app_logo.png" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#199A8E"

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
